const invokePowerShellCommandScript = [
  "$ErrorActionPreference = 'Stop'",
  "$modulePath = $env:PS2MCP_MODULE_PATH",
  "$profilePath = $env:PS2MCP_PROFILE_PATH",
  "$sourceCommand = $env:PS2MCP_SOURCE_COMMAND",
  "$serializationDepth = [int]$env:PS2MCP_SERIALIZATION_DEPTH",
  "$argumentsJson = [Console]::In.ReadToEnd()",
  "$arguments = if ([string]::IsNullOrWhiteSpace($argumentsJson)) { @{} } else { ConvertFrom-Json -InputObject $argumentsJson -AsHashtable }",
  "if (-not [string]::IsNullOrWhiteSpace($profilePath)) {",
  "if (-not (Test-Path -LiteralPath $profilePath -PathType Leaf)) {",
  "throw \"Bootstrap profile file not found: $profilePath\"",
  "}",
  "try {",
  ". $profilePath",
  "}",
  "catch {",
  "throw \"Bootstrap profile failed: $($_.Exception.Message)\"",
  "}",
  "}",
  "Import-Module -Force $modulePath",
  "$result = & $sourceCommand @arguments",
  "$result | ConvertTo-Json -Depth $serializationDepth -Compress",
].join("; ");